### ISSUE TITLE
与Meteor Client冲突

### ISSUE THREAD

**Issue by TanChenyu** [cdqtzrc/Carpet-Org-Addition#3]
日志：
```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-01-01 11:35:42
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fabric-renderer-indigo'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.minecraft.class_4668.<clinit>(class_4668.java:126)
	at net.fabricmc.fabric.api.renderer.v1.material.BlendMode.<clinit>(BlendMode.java:33)
	at net.fabricmc.fabric.impl.client.indigo.renderer.material.MaterialViewImpl.<clinit>(MaterialViewImpl.java:32)
	at net.fabricmc.fabric.impl.client.indigo.renderer.IndigoRenderer.materialFinder(IndigoRenderer.java:54)
	at net.fabricmc.fabric.impl.client.indigo.renderer.IndigoRenderer.<clinit>(IndigoRenderer.java:37)
	at net.fabricmc.fabric.impl.client.indigo.Indigo.onInitializeClient(Indigo.java:145)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 12 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 19 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 23 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method updateTargetedEntityModifySquaredMaxReach(D)D in meteor-client.mixins.json:GameRendererMixin from mod meteor-client failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap meteor-client-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 27 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:487)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:高级 Windows 32 基本 API:6.1.7601.24384 (win7sp1_ldr_escrow.190220-1800):Microsoft Corporation
		CLBCatQ.DLL:COM+ Configuration Catalog:2001.12.8530.16385 (win7_rtm.090713-1255):Microsoft Corporation
		COMCTL32.dll:用户体验控件库:6.10 (win7_rtm.090713-1255):Microsoft Corporation
		CRYPT32.dll:加密 API32:6.1.7601.24382 (win7sp1_ldr.190210-0600):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:6.1.7601.24384 (win7sp1_ldr_escrow.190220-1800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:6.1.7601.24382 (win7sp1_ldr.190210-0600):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:6.1.7601.17514 (win7sp1_rtm.101119-1850):Microsoft Corporation
		DNSAPI.dll:DNS 客户端 API DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		GDI32.dll:GDI Client DLL:6.1.7601.23914 (win7sp1_ldr.170908-0600):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		KERNELBASE.dll:Windows NT 基本 API 客户端 DLL:6.1.7601.17965 (win7sp1_gdr.121004-0333):Microsoft Corporation
		LPK.dll:Language Pack:6.1.7601.23974 (win7sp1_ldr.171213-0600):Microsoft Corporation
		MSASN1.dll:ASN.1 Runtime APIs:6.1.7601.17514 (win7sp1_rtm.101119-1850):Microsoft Corporation
		MSCTF.dll:MSCTF 服务器 DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:6.1.7601.24000 (win7sp1_ldr.171231-1547):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:6.1.7601.23889 (win7sp1_ldr.170810-1615):Microsoft Corporation
		OLEAUT32.dll::6.1.7601.23775:Microsoft Corporation
		PSAPI.DLL:Process Status Helper:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		Pdh.dll:Windows 性能数据助手 DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		RPCRT4.dll:远程过程调用运行时:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		RpcRtRemote.dll:Remote RPC Extension:6.1.7601.17514 (win7sp1_rtm.101119-1850):Microsoft Corporation
		SHELL32.dll:Windows 外壳公用 DLL:6.1.7601.17514 (win7sp1_rtm.101119-1850):Microsoft Corporation
		SHLWAPI.dll:外壳简易实用工具库:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		SafeWrapper.dll
		USER32.dll:多用户 Windows 用户 API 客户端 DLL:6.1.7601.17514 (win7sp1_rtm.101119-1850):Microsoft Corporation
		USERENV.dll:Userenv:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		USP10.dll:Uniscribe Unicode script processor:1.0626.7601.23894 (win7sp1_ldr.170816-0600):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		WINHTTP.dll:Windows HTTP 服务:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		WININET.dll:Win32 的 Internet 扩展:11.00.9600.19267 (winblue_ltsb_escrow.190125-1255):Microsoft Corporation
		WINMM.dll:MCI API DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		WINNSI.DLL:Network Store Information RPC interface:6.1.7601.23889 (win7sp1_ldr.170810-1615):Microsoft Corporation
		WLDAP32.dll:Win32 LDAP API DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32 位 DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		api-ms-win-core-file-l1-2-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-core-file-l2-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-core-localization-l1-2-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-core-processthreads-l1-1-1.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-core-synch-l1-2-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-core-timezone-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-convert-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-environment-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-filesystem-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-heap-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-locale-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-math-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-runtime-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-stdio-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-string-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-time-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-utility-l1-1-0.dll:ApiSet Stub DLL:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-downlevel-advapi32-l1-1-0.dll:ApiSet Stub DLL:6.2.9200.16492 (win8_gdr_oobssr.130113-0015):Microsoft Corporation
		api-ms-win-downlevel-normaliz-l1-1-0.dll:ApiSet Stub DLL:6.2.9200.16492 (win8_gdr_oobssr.130113-0015):Microsoft Corporation
		api-ms-win-downlevel-ole32-l1-1-0.dll:ApiSet Stub DLL:6.2.9200.16492 (win8_gdr_oobssr.130113-0015):Microsoft Corporation
		api-ms-win-downlevel-shlwapi-l1-1-0.dll:ApiSet Stub DLL:6.2.9200.16492 (win8_gdr_oobssr.130113-0015):Microsoft Corporation
		api-ms-win-downlevel-user32-l1-1-0.dll:ApiSet Stub DLL:6.2.9200.16492 (win8_gdr_oobssr.130113-0015):Microsoft Corporation
		api-ms-win-downlevel-version-l1-1-0.dll:ApiSet Stub DLL:6.2.9200.16492 (win8_gdr_oobssr.130113-0015):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		bcrypt.dll:Windows Cryptographic Primitives Library:6.1.7601.24384 (win7sp1_ldr_escrow.190220-1800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP 客户端服务:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 客户端:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec 用户模式 API:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		iertutil.dll:Run time utility for Internet Explorer:11.00.9600.19267 (winblue_ltsb_escrow.190125-1255):Microsoft Corporation
		java.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.3.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jna10223517684124459228.dll:JNA native library:6.1.6:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.3.0:Microsoft
		kernel32.dll:Windows NT 基本 API 客户端 DLL:6.1.7601.17965 (win7sp1_gdr.121004-0333):Microsoft Corporation
		libjlw-1.3.2.dll
		libzdtp64.dll::1, 0, 0, 1320:
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.7601.17744 (win7sp1_gdr.111215-1535):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 服务提供程序:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		napinsp.dll:电子邮件命名填充提供程序:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		ncrypt.dll:Windows 加密库:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		normaliz.DLL:Unicode Normalization DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		ntdll.dll:NT 层 DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA 提供程序:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		ole32.dll:用于 Windows 的 Microsoft OLE:6.1.7601.24168 (win7sp1_ldr.180608-0600):Microsoft Corporation
		perfos.dll:Windows 系统性能对象 DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		pnrpnsp.dll:PNRP 命名空间提供程序:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		profapi.dll:User Profile Basic API:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		ucrtbase.DLL:Microsoft® C Runtime Library:10.0.22000.194 (WinBuild.160101.0800):Microsoft Corporation
		urlmon.dll:Win32 的 OLE32 扩展:11.00.9600.19267 (winblue_ltsb_escrow.190125-1255):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		webio.dll:Web 传输协议 API:6.1.7601.17514 (win7sp1_rtm.101119-1850):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		wship6.dll:Winsock2 帮助程序 DLL (TL/IPv6):6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		wshtcpip.dll:Winsock2 帮助程序 DLL (TL/IPv4):6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 396724096 bytes (378 MiB) / 807403520 bytes (770 MiB) up to 2577399808 bytes (2458 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 970
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x13c2
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7381
	Graphics card #1 name: Intel(R) HD Graphics 4600
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x0412
	Graphics card #1 versionInfo: DriverVersion=10.18.14.5180
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: Unknown
	Virtual memory max (MB): 20027.01
	Virtual memory used (MB): 8396.05
	Swap memory total (MB): 11998.14
	Swap memory used (MB): 1.00
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx2457m
	Fabric Mods: 
		carpet: Carpet Mod 1.4.128+v231205
		carpet-org-addition: Carpet Org Addition 1.19.2
		carpet-tis-addition: Carpet TIS Addition 1.54.4
			conditional-mixin: conditional mixin 0.4.1
		fabric-api: Fabric API 0.92.0+1.20.4
			fabric-api-base: Fabric API Base 0.4.35+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.45+78d798af4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.15+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.14+78d798af4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.3+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.45+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.6+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.40+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.19+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.57+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.9+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.9+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.22+78d798af4f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.17+78d798af4f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.60+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.28+4ced05924f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.0+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.71+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.45+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.1.34+78d798af4f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.20+78d798af4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.40+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.38+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.29+78d798af4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.4+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.4+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.59+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.7+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.6+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.2+78d798af4f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.8+06274a474f
			fabric-particles-v1: Fabric Particles (v1) 1.1.6+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.15+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.13+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.3+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.3+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.50+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.41+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.32+78d798af4f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.53+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.12+78d798af4f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.13+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.15+78d798af4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.16+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.50+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.16+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.6+78d798af4f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.13+78d798af4f
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		gca: GugleCarpetAddition 2.7.0-1.20.4
		java: OpenJDK 64-Bit Server VM 17
		litematica: Litematica 0.17.0
		malilib: MaLiLib 0.18.0
		meteor-client: Meteor Client 0.5.6-1992
		minecraft: Minecraft 1.20.4
		minihud: MiniHUD 0.30.0
		viafabricplus: ViaFabricPlus 3.0.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 4.9.2-SNAPSHOT
			com_viaversion_viaversion-common: viaversion-common 4.9.3-SNAPSHOT
			de_florianmichael_classic4j: Classic4J 2.0.1
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.3
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.3
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.3
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_mcping: MCPing 1.3.0
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.0
			net_lenni0451_mcstructs-bedrock_text: text 1.2.0
			net_lenni0451_mcstructs_core: core 2.4.1
			net_lenni0451_mcstructs_nbt: nbt 2.4.1
			net_lenni0451_mcstructs_snbt: snbt 2.4.1
			net_lenni0451_mcstructs_text: text 2.4.1
			net_lenni0451_reflect: Reflect 1.3.1
			net_raphimc_minecraftauth: MinecraftAuth 3.0.1-SNAPSHOT
			net_raphimc_viaaprilfools: ViaAprilFools 2.0.11-SNAPSHOT
			net_raphimc_viabedrock: ViaBedrock 0.0.4-SNAPSHOT
			net_raphimc_vialegacy: ViaLegacy 2.2.22-SNAPSHOT
			net_raphimc_vialoader: ViaLoader 2.2.13-SNAPSHOT
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR1-SNAPSHOT
			org_yaml_snakeyaml: snakeyaml 2.2
	Launched Version: 1.20.4
	Launcher name: PCL
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: zh_CN
	CPU: <unknown>

-- Meteor Client --

Version: 0.5.6
Dev Build: 1992

```

**Comment by cdqtzrc** [comment]
问题出在GameRendererMixin这个类中，这个类用来修改玩家与实体的交互距离，与彗星端不兼容，因为它修改了一些常量

**Comment by cdqtzrc** [comment]
修复了

**Comment by TanChenyu** [comment]
> 修复了

谢谢
（真没想到作者会修复这个）

**Comment by cdqtzrc** [comment]
> > 修复了
> 
> 谢谢 （真没想到作者会修复这个）

嗯，我也没想到我会修这个，只是这几段代码对兼容性的影响比较大，就算你不提交我也会改的，另外 #5 也是因为同样的问题
